<?php 
/* 	
If you see this text in your browser, PHP is not configured correctly on this hosting provider. 
Contact your hosting provider regarding PHP configuration for your site.

PHP file generated by Adobe Muse CC 2017.0.4.363
*/

require_once('form_process.php');

$form = array(
	'subject' => 'Envío de Formulario Cómo Colaborar',
	'heading' => 'Envío de nuevo formulario',
	'success_redirect' => '',
	'resources' => array(
		'checkbox_checked' => 'Marcada',
		'checkbox_unchecked' => 'No marcada',
		'submitted_from' => 'Formulario enviado desde el sitio web: %s',
		'submitted_by' => 'Dirección IP del visitante: %s',
		'too_many_submissions' => 'Se han realizado recientemente demasiados envíos a través de esta IP',
		'failed_to_send_email' => 'Error al enviar el correo electrónico',
		'invalid_reCAPTCHA_private_key' => 'Clave privada de reCAPTCHA no válida.',
		'invalid_reCAPTCHA2_private_key' => 'Clave privada de reCAPTCHA 2.0 no válida.',
		'invalid_reCAPTCHA2_server_response' => 'Respuesta de servidor de reCAPTCHA 2.0 no válida.',
		'invalid_field_type' => 'Tipo de campo desconocido: %s.',
		'invalid_form_config' => 'El campo \'%s\' contiene una configuración no válida.',
		'unknown_method' => 'Método de solicitud de servidor desconocido'
	),
	'email' => array(
		'from' => 'contacto@fundacioncristovive.cl',
		'to' => 'contacto@fundacioncristovive.cl'
	),
	'fields' => array(
		'custom_U71007' => array(
			'order' => 1,
			'type' => 'string',
			'label' => 'Nombres',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Nombres\' es obligatorio.'
			)
		),
		'Email' => array(
			'order' => 4,
			'type' => 'email',
			'label' => 'Correo electrónico',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Correo electrónico\' es obligatorio.',
				'format' => 'El campo \'Correo electrónico\' contiene un correo electrónico no válido.'
			)
		),
		'custom_U70998' => array(
			'order' => 3,
			'type' => 'string',
			'label' => 'Rut',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Rut\' es obligatorio.'
			)
		),
		'custom_U71003' => array(
			'order' => 5,
			'type' => 'string',
			'label' => 'Teléfono',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Teléfono\' es obligatorio.'
			)
		),
		'custom_U71012' => array(
			'order' => 2,
			'type' => 'string',
			'label' => 'Apellidos',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Apellidos\' es obligatorio.'
			)
		),
		'custom_U117116' => array(
			'order' => 7,
			'type' => 'string',
			'label' => 'Mensaje',
			'required' => true,
			'errors' => array(
				'required' => 'El campo \'Mensaje\' es obligatorio.'
			)
		),
		'custom_U71017' => array(
			'order' => 6,
			'type' => 'radiogroup',
			'label' => 'Donación mensual',
			'required' => true,
			'optionItems' => array(
				'$3.000',
				'$5.000',
				'$10.000',
				'$20.000',
				'Otro monto'
			),
			'errors' => array(
				'required' => 'El campo \'Donación mensual\' es obligatorio.',
				'format' => 'El campo \'Donación mensual\' contiene un valor no válido.'
			)
		),
		'custom_U70989' => array(
			'order' => 8,
			'type' => 'radiogroup',
			'label' => 'Formas de pago',
			'required' => true,
			'optionItems' => array(
				'PAC',
				'PAT'
			),
			'errors' => array(
				'required' => 'El campo \'Formas de pago\' es obligatorio.',
				'format' => 'El campo \'Formas de pago\' contiene un valor no válido.'
			)
		)
	)
);

process_form($form);
?>
